function createfigure(xvector1, ymatrix1, X1, Y1, X2, Y2)
%CREATEFIGURE(xvector1, ymatrix1, X1, Y1, X2, Y2)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 09-Apr-2021 23:23:54

% Create figure
figure1 = figure;

% Create textbox
annotation(figure1,'textbox',...
    [0.634197480810421 0.64566393421522 0.07339446366782 0.0370370370370372],...
    'String','mu = 19.32',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.299773932159561 0.637621038772861 0.07339446366782 0.0370370370370372],...
    'String','mu = 17.06',...
    'FitBoxToText','off');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0813148788927336 0.111111111111111 0.877162629757786 0.813888888888888]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'SeriesIndex',2,...
    'DisplayName','concentrations(room temp) NormalDist',...
    'LineWidth',2,...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'DisplayName','concentrations(when heated) NormalDist',...
    'LineWidth',2,...
    'Color',[1 0 0]);

% Create ylabel
ylabel({'Frequency'});

% Create xlabel
xlabel({'Chemical Concentration'});

% Create title
title({'Table I','Comparison of Normal distributions of chemical concentrations at room temperature and when heated to higher temperature'});

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'BarWidth',1);
set(bar1(2),'DisplayName','room temp chemicals concs',...
    'FaceColor',[0.349019607843137 0.596078431372549 0.76078431372549]);
set(bar1(1),'DisplayName','heated chemical concs',...
    'FaceColor',[0.768627450980392 0.396078431372549 0.301960784313725]);
baseline1 = get(bar1(2),'BaseLine');
set(baseline1,'Visible','on');

hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XTick',...
    [15 15.5 16 16.5 17 17.5 18 18.5 19 19.5 20 20.5 21 21.5 22 22.5 23 23.5 24 24.5 25],...
    'XTickLabel',...
    {'15','15.5','16','16.5','17','17.5','18','18.5','19','19.5','20','20.5','15','15.5','16','16.5','23','15','24','24.5','25'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.760021866515309 0.821933564421007 0.219950934998441 0.0931635363172268]);
uistack(histfit(ccr1),'top');


